### ISSUE TITLE
Remove hard coded AV Scan score card

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/submission-processor#21]
[This line was hard coded for the short term](https://github.com/topcoder-platform/submission-processor/blob/develop/src/services/ProcessorService.js#L18) to get things tested.

I'd like to go back and make this dynamic via a call to the API for that Review Type

**Comment by cwdcwd** [comment]
@sharathkumaranbu @callmekatootie check this one out

**Comment by BadalZ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove hard coded parameters from Sub Processor](https://trello.com/c/VLMcfHo4/35-remove-hard-coded-parameters-from-sub-processor)
